name: business_dot_com
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  google_fonts: ^6.2.1
  animated_notch_bottom_bar: ^1.0.3
  motion_tab_bar: ^2.0.4
  motion_tab_bar_v2: ^0.3.0
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.2
  intl: 0.19.0
  image_picker: ^0.8.7+4
  smooth_page_indicator: ^1.2.0+3
  firebase_storage: ^12.3.6
  simple_gradient_text: ^1.3.0
  url_launcher: ^6.3.1
  flutter_year_picker: ^0.0.1
  month_year_picker: ^0.4.0+1
  http: ^1.3.0
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/registration_form/
    - assets/images/logos/
    - assets/Gov_schemes_logo/
    - assets/login_and_signup/
    - assets/drawer/
    - assets/drawer/help_support/
    
  fonts:
    - family: Bulletto
      fonts:
        - asset: fonts/Bulletto Killa.ttf
