const List<String> domainlist = <String>[
  'Select Domain',
  'Information Technology (IT) and Software',
  'Telecommunications',
  'Automobile',
  'Banking and Financial Services',
  'Healthcare and Pharmaceuticals',
  'Retail and E-commerce',
  'Energy and Power',
  'Consumer Goods and FMCG',
  'Real Estate and Infrastructure',
  'Education and EdTech',
  'Hospitality and Tourism',
  'Media and Entertainment',
  'Agriculture and Agri-Tech',
  'Manufacturing and Industrial Goods',
  'Logistics and Supply Chain',
  'Aerospace and Defence',
  'Chemicals and Petrochemicals',
  'Financial Technology (FinTech)',
  'Legal and Consulting Services',
  'Environmental and Waste Management',
  'Textiles and Apparel',
  'Food and Beverage (F&B)',
  'Technology and Electronics',
  'Space and Satellite',
  'Retail Banking and Microfinance',
  'Sports and Fitness',
  'Luxury and Lifestyle',
  'Pharmaceutical and Biotech Research',
  'Construction and Engineering',
  'Waste to Energy',
  'Artificial Intelligence (AI) and Robotics',
  'Cybersecurity',
  'Digital Marketing and Advertising',
  'Human Resources and Recruitment',
  'Arts',
  'Culture, and Creative Industries',
  'Environmental Sustainability',
  'Insurance',
  'Supply Chain and Procurement Services',
  'Pet Care and Veterinary Services',
  'Waste Recycling and Circular Economy',
  'Financial Auditing and Accounting Services',
  'Event Management and Conferences',
  'Cloud Computing and Hosting Services',
  'Transportation and Shipping',
  'Water Purification and Management',
  'Construction Materials and Cement',
  'Tourism and Travel Services',
  'Gaming and eSports',
  'Retail Consumer Electronics',
  'Packaging',
  'Biotechnology and Life Sciences',
  'Petroleum and Natural Gas',
  'Mining and Metals',
  'Civil Aviation',
  'Marine and Shipping',
  'Luxury Real Estate and Property Development',
  'Public Sector Enterprises (PSUs)',
  'Social Impact and Non-Profit',
  'Cryptocurrency and Blockchain',
  'Agricultural Equipment and Technology',
  'Smart Home and IoT (Internet of Things)',
  'Social Media and Online Content Creation',
  'Electric Vehicles (EVs) and Clean Energy',
  '3D Printing and Additive Manufacturing',
  'Security Services and Systems',
];
